name: Build Dotnet ASP Base Image

on: 
  # schedule:
  #   - cron: '30 1 * * 6'
  workflow_dispatch:

jobs:  
  build:
    name: Build Image
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: dotnet-asp-base

    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v2
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ap-south-1

    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        # docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:unapproved BaseImages/dotnet-asp -f BaseImages/dotnet-asp/Dockerfile
        docker build -t $ECR_REPOSITORY:unapproved BaseImages/dotnet-asp -f BaseImages/dotnet-asp/Dockerfile 
        # docker push $ECR_REGISTRY/$ECR_REPOSITORY:unapproved

    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.ECR_REPOSITORY }}:unapproved'
        format: 'sarif'
        output: 'results.sarif'
        severity: 'CRITICAL,HIGH'
    
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'results.sarif'

    
    # - name: Send Slack Notification
    #   uses: slackapi/slack-github-action@v1.23.0
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    #   with:
    #     payload-file-path: "./results.json"
    
    # - name: Send Slack Notification
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    #   run: |
    #     curl -X POST -H 'Content-type: application/json' --data @results.json ${{ env.SLACK_WEBHOOK_URL }}